runtime: python310
entrypoint: gunicorn -b :$PORT main:app
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 3
handlers:
  - url: /.*
    script: auto
env_variables:
  FRONTEND_ORIGIN: "https://your-streamlit-app.streamlit.app"
