# fly.toml — EduMate Backend (FastAPI/Uvicorn)
# Cloud-native deployment configuration for Fly.io
# 
# Deploy from backend directory with: fly deploy

app = "edumate-local"            # Change if taken (also update Streamlit API base URL)
primary_region = "lhr"           # London (pick nearest: lhr, iad, syd, etc.)

# Environment variables (non-sensitive)
[env]
  PORT = "8080"
  FAST_MODE = "1"
  MAX_ACTIVE_GENERATIONS = "1"
  TEMP = "0.3"
  NUM_PREDICT = "400"
  ENABLE_CONVERSATION_MEMORY = "1"
  MAX_CONVERSATION_HISTORY = "10"
  OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
  OPENROUTER_MODEL = "openai/gpt-3.5-turbo"
  OPENROUTER_APP_NAME = "EduMate"

# IMPORTANT: Set secrets via CLI (not in this file!)
# fly secrets set OPENROUTER_API_KEY=your-api-key-here

# Use Dockerfile in current directory (backend/)
[build]
  dockerfile = "Dockerfile"

# HTTP service configuration (Fly.io v2)
[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true     # Wake on request
  auto_stop_machines = true      # Sleep when idle (saves costs)
  min_machines_running = 0       # Scale to zero when idle
  
  # Concurrency limits
  [http_service.concurrency]
    type = "requests"
    soft_limit = 5
    hard_limit = 10

# Health check endpoint
[[checks]]
  name = "health"
  type = "http"
  port = 8080
  method = "get"
  path = "/health"
  interval = "15s"
  timeout = "2s"
  grace_period = "10s"
