cat > backend/fly.toml << "a"
# fly.toml — EduMate Backend (FastAPI/Uvicorn)

app = "edumate-local"            # <--- change if taken (also update your Streamlit API base URL)
primary_region = "lhr"           # London (pick your nearest: lhr, iad, syd, etc.)

# Optional env that your app expects. Do NOT put secrets here.
[env]
  PORT = "8080"                  # uvicorn will listen on this port

# We’re using the Dockerfile in this folder (backend/)
[build]
  dockerfile = "Dockerfile"

# Modern Machines config for HTTP apps
[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true     # wake on request
  auto_stop_machines = true      # sleep when idle (saves free-tier minutes)
  min_machines_running = 0
  concurrency = { type = "requests", soft_limit = 5, hard_limit = 10 }

# Simple health check (FastAPI should serve GET /health with 200 OK)
[checks]
  [checks.health]
    type = "http"
    port = 8080
    method = "get"
    path = "/health"
    interval = "15s"
    timeout  = "2s"

