# fly.toml - Fly.io configuration for EduMate Backend API
# 
# ⚠️ FREE TIER CONFIGURATION ⚠️
# This configuration is optimized for Fly.io's free tier to ensure NO CHARGES.
# 
# Free tier includes:
# - 3 shared-cpu-1x VMs with 256MB RAM each
# - 160GB outbound data transfer per month
# - Automatic start/stop to conserve resources
# 
# IMPORTANT: Monitor your usage at https://fly.io/dashboard
# To set spending limits: fly orgs billing-limits set
# To check current usage: fly billing show

app = "edumate-local"
primary_region = "iad"  # Change to your nearest region (iad=US East, lhr=London, syd=Sydney)

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true   # ✅ Auto-stop when idle to save resources
  auto_start_machines = true  # ✅ Auto-start on incoming requests
  min_machines_running = 0    # ✅ Allow scaling to zero when idle

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    timeout = "10s"

# Free tier VM configuration: 256MB RAM, 1 shared CPU
[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

# Environment variables
[env]
  PORT = "8000"
  FAST_MODE = "1"                    # Enable fast mode for better performance
  MAX_ACTIVE_GENERATIONS = "1"       # Limit concurrent requests on free tier
  USE_OPENAI = "1"                   # Use OpenRouter instead of Ollama
  OPENAI_BASE_URL = "https://openrouter.ai/api/v1"
  OPENAI_MODEL = "openai/gpt-3.5-turbo"

# ⚠️ NO PERSISTENT VOLUMES - Data will be ephemeral
# For production with persistent data, you would need:
# [[mounts]]
#   source = "edumate_data"
#   destination = "/app/chroma_db"
# But this requires paid storage on Fly.io

# ⚠️ NO PAID ADD-ONS ENABLED
# No databases, no Redis, no object storage

##############################################################################
# DEPLOYMENT INSTRUCTIONS:
#
# 1. Install flyctl CLI: https://fly.io/docs/hands-on/install-flyctl/
# 2. Login: fly auth login
# 3. Deploy: fly launch (or fly deploy after first launch)
# 4. Check logs: fly logs
# 5. Monitor usage: fly billing show
# 6. Set spending cap: fly orgs billing-limits set
#
# IMPORTANT NOTES:
# - This backend depends on Ollama for LLM generation, which is not included
# - You may need to modify the code to use cloud LLM APIs (OpenAI, Anthropic)
#   or remove Ollama dependency for cloud deployment
# - The ChromaDB vector database will be ephemeral (data lost on restart)
# - For persistent storage, consider using external services or paid volumes
#
# UPDATING FRONTEND:
# After deployment, update the API_BASE environment variable in your Streamlit
# frontend to point to: https://edumate-local.fly.dev
# Example: export API_BASE=https://edumate-local.fly.dev
##############################################################################
